dataset: ImageNet
res: 128
model: ConvNetD5
device: [7]
ipc: 200
syn_steps: 20
expert_epochs: 2
lr_img: 10000
lr_teacher: 0.01
ema_decay: 0.9995
Iteration: 10000
batch_syn: 32
num_eval: 1
eval_it: 500
skip_first_eva: True
lr_y: 2.0
Momentum_y: 0.9
threshold: 500.
pix_init: samples_predicted_correctly
batch_train: 128

Sequential_Generation: False
min_start_epoch: 40
max_start_epoch: 60

lr_lr: 0.000001
zca: False # do not use zca when distilling ImageNet Subsets

